### ISSUE TITLE
Issues e PR de erros do site em várias línguas

### ISSUE THREAD

**Issue by ericbrasiln** [ericbrasiln/git-gh-workflow#28]
Erros encontrados na página de [diretrizes para revisores](https://programminghistorian.org/en/editor-guidelines) em todos os idiomas. Existem incoerências entre as informações e erros em links internos no markdown.

- [x] No tópico [5) Confirmar se todos os links e cabeçalhos YAML funcionam corretamente](https://programminghistorian.org/pt/directrizes-editor#5-confirmar-se-todos-os-links-e-cabe%C3%A7alhos-yaml-funcionam-corretamente) há uma incoerência com a versão em inglês/espanhol/francês. Nos outros idiomas a informação que consta é que o “site será automaticamente testado pelo Travis CI”. Enquanto na versão em português, a informação é que o site “será automaticamente testado pelo GitHub Actions”. (JULGO QUE O ERRO ESTÁ NAS VERSÕES NOUTRAS LÍNGUAS POIS ACTUALMENTE A VERIFICAÇÃO É FEITA COM O GIT-HUB ACTIONS)
    - [x] Corrigir a versão em inglês: https://programminghistorian.org/en/editor-guidelines#5-confirm-all-links-and-yaml-headers-are-functioning-correctly
    - [x] Corrigir a versão em espanhol: https://programminghistorian.org/en/editor-guidelines#5-confirm-all-links-and-yaml-headers-are-functioning-correctly
    - [x] corrigir a versão em francês: https://programminghistorian.org/en/editor-guidelines#5-confirm-all-links-and-yaml-headers-are-functioning-correctly
- [x] Ainda nesse tópico há um erro que está presente na versão em inglês e português: na primeira lista não ordenada do tópico, no primeiro item da lista, o link para “[O restante desta lição pode ser ignorado e passar directamente para a secção de agradecimento.](https://programminghistorian.org/pt/directrizes-editor#11-thank-everyone-and-encourage-promotion)” está errado. o correto é: “[https://programminghistorian.org/pt/directrizes-editor#6-informar-o-editor](https://programminghistorian.org/pt/directrizes-editor#6-informar-o-editor)”. Importante destacar que esse erro também esta presente nas versão dos demais idiomas: (CONCORDO)
     - [x] inglês, sendo o link correto: [https://programminghistorian.org/en/editor-guidelines#6-inform-the-editor](https://programminghistorian.org/en/editor-guidelines#6-inform-the-editor)
     - [x] espanhol: [https://programminghistorian.org/es/guia-editor#5-informa-al-editor](https://programminghistorian.org/es/guia-editor#5-informa-al-editor)
          - [x] Há outro erro em espanhol: a numeração desse item deveria ser “6)” e não “5)”. E nesse caso o link correto será: [https://programminghistorian.org/es/guia-editor#6-informa-al-editor](https://programminghistorian.org/es/guia-editor#5-informa-al-editor)
    - [x] francês: [https://programminghistorian.org/fr/consignes-redacteurs#5-tenir-au-courant-le-r%C3%A9dacteur-ou-la-r%C3%A9dactrice-en-charge-du-suivi-%C3%A9ditorial-de-la-le%C3%A7on](https://programminghistorian.org/fr/consignes-redacteurs#5-tenir-au-courant-le-r%C3%A9dacteur-ou-la-r%C3%A9dactrice-en-charge-du-suivi-%C3%A9ditorial-de-la-le%C3%A7on)

**Comment by ericbrasiln** [comment]
Propostas e alterações realizadas: https://github.com/programminghistorian/jekyll/pull/2835
